on:
  push:
    branches: 
     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false

    # Install dependencies
    - name: Set up Python 3.7
      uses: conda-incubator/setup-miniconda@v1 
      with:
          activate-environment: condaenv
          environment-file: environment.yml
          auto-update-conda: true
          python-version: 3.7
          auto-activate-base: false
  
    - shell: bash -l {0}
      run: |
          conda env update -n condaenv --file environment.yml
          conda info
          conda list

    # Build the book
    - name: Build the book
      shell: bash -l {0}
      run: |
          jupyter-book build mini_book/

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: mini_book/_build/html

